post_index:
    path: /
    defaults: { _controller: app.controller.post_index:index }

post_new:
    path: /post/new
    defaults: { _controller: app.controller.new_post:create }
    methods: [POST, GET]

post_edit:
    path: /post/edit/{id}
    defaults: { _controller: app.controller.update_post:update }
    methods: [POST, GET]

post_show:
    path: /post/show/{id}
    defaults: { _controller: app.controller.show_post:show }
    methods: [GET]
