AppBundle\Post\Post:
    type: entity
    table: post
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        message:
            type: text
        dateCreate:
            type: datetime
